Flink pipe
majercakdavid/stock-sentiment-analysis pull request #3
Opened 2020-01-31 22:04 UTC by viktorria

2020-02-04 20:44 UTC, majercakdavid requested changes

2020-02-04 20:44 UTC, majercakdavid commented on .gitignore
> +**/target/**/*
What is the difference? Why did this file change?

2020-02-04 20:44 UTC, majercakdavid commented on flink-processing/flink-processing/src/main/scala/Main.scala
> +    val kafkaProducer = new KafkaFlinkProducer("tweets-analysed")
Will not it be results? Should not it be something like tweets-results/tweets-processed?

2020-02-04 20:44 UTC, majercakdavid commented on flink-processing/flink-processing/src/main/scala/KafkaFlinkConsumer.scala
> +    properties.setProperty("zookeeper.connect", "localhost:2181")
Read it from environment do not make it hard-coded.

2020-02-04 20:44 UTC, majercakdavid commented on flink-processing/flink-processing/src/main/scala/KafkaFlinkProducer.scala
> +    properties.setProperty("zookeeper.connect", "localhost:2181")
Just like the one above

2020-02-04 21:55 UTC, viktorria commented on .gitignore
> +**/target/**/*
It is not in the changed files. It comes from merging your branch into mine.

2020-02-04 21:57 UTC, viktorria commented on flink-processing/flink-processing/src/main/scala/Main.scala
> +    val kafkaProducer = new KafkaFlinkProducer("tweets-analysed")
I wanted to have a new channel that describes what was done with tweets. And we have analysed their sentiment, so they will be analysed. There is no result in this case.

2020-02-04 22:00 UTC, viktorria commented on flink-processing/flink-processing/src/main/scala/KafkaFlinkConsumer.scala
> +    properties.setProperty("zookeeper.connect", "localhost:2181")
I have followed project twitter-kafka-scala where properties for producer/consumer are also hard-coded. We can make a new branch to add environments and change it in all projects?

2020-02-04 22:00 UTC, viktorria commented on flink-processing/flink-processing/src/main/scala/KafkaFlinkConsumer.scala
> +    properties.setProperty("zookeeper.connect", "localhost:2181")
Or do you prefer to change it here? before merge?

2020-02-09 21:00 UTC, majercakdavid commented on flink-processing/flink-processing/src/main/scala/Main.scala
> +    val kafkaProducer = new KafkaFlinkProducer("tweets-analysed")
The job has side effects on the passed in data and therefore the analysed word is misleading

2020-02-09 21:12 UTC, merged